FROM wordpress:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends libzip-dev \
    && docker-php-ext-install ftp \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*